# Generated by Django 3.0 on 2021-01-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=100)),
                ('truck_location', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100, null=True)),
                ('geo_location', models.CharField(max_length=100, null=True)),
                ('truck_opening_time', models.CharField(max_length=20, null=True)),
                ('truck_closing_time', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
